name: Pulumi Infrastructure Safety Check

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  preview:
    name: Pulumi Preview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::655236339481:role/GitHubPulumiNewRunRole
          aws-region: eu-central-1
          role-session-name: GitHubActionsPulumiPreview
          audience: sts.amazonaws.com

      - name: Run Pulumi Preview
        uses: pulumi/actions@v7
        with:
          command: preview
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}